services:
  - type: web
    name: tasknest-web
    runtime: node
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://tasknest_db_tmsz_user:mP7Aegx1H1nihTbgfwifNV94fX5LnWqD@dpg-d7jip82qqhas73d29b2g-a/tasknest_db_tmsz
      - key: JWT_SECRET
        value: tasknest_super_secret_jwt_2024_xyz
      - key: FRONTEND_URL
        value: https://tasknest-1-k5lf.onrender.com