services:
  - type: web
    name: tasknest-web
    env: node
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tasknest-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  - type: pgsql
    name: tasknest-db
    plan: free
